### ISSUE TITLE
missing the zeroth law

### ISSUE THREAD

**Issue by patrickkettner** [hubotio/hubot-rules#1]
http://en.wikipedia.org/wiki/Three_Laws_of_Robotics#Zeroth_Law_added

![](http://oyster.ignimgs.com/wordpress/stg.ign.com/2014/05/abed-canon-3.gif)

**Comment by technicalpickles** [comment]
I know it's a small change, but if you wanted to do a PR to add it, it would be appreciated :sparkles:

**Comment by patrickkettner** [comment]
with pleasure!
